services:
  postgres:
    image: postgres:latest
    container_name: tamagotchi_db
    ports:
      - 5432:5432
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tamagotchi_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=abcd
